# 账号设置
account:
    # bot 账号
    bot: *你机器人的 QQ 号*
    # 管理员账号
    admin: *你的 QQ 号*
    # 封闭测试群设置
    group:
        # 封闭测试群群号
        groupId: *用于封闭测试的 QQ 群的群号*
        # 封闭测试开关
        closeBeta: false

# mirai-api-http 配置
miraiApi:
    # IP 地址
    # 如果你的 mirai-api-http 在其他服务器上运行，请填写那台服务器的公网 IP（真的会有人这么干吗？！）
    host: 0.0.0.0
    # 端口
    port:
        # http 服务端口
        http: 8080
        # websocket 服务端口
        ws: 8060
    # authkey
    authKey: *你的 mirai-api-http 的 authkey*
    # mirai-console 的根目录路径，可为空，用于通过 path 参数发送静态文件。不配置的情况下，默认通过上传的方式发送
    folder:

# Amiya-Bot console IP 和端口配置
console:
    # 监听的 IP 地址，不要填写公网 IP ！！！建议此项不要变动，如想进一步保证安全，可改为 127.0.0.1 以使后台仅能由本地访问
    host: 0.0.0.0
    # 监听的端口，范围 1-65535
    port: 80

# 百度智能云配置
baiduCloud:
    # 由百度智能云提供的增强功能开关
    enable: false
    appId:
    apiKey:
    secretKey:

# 消息设置
message:
    # 消息限制
    # seconds 意为秒，在这里指在...秒内；maxCount 意为最大消息数，在...秒内所允许的最大消息数
    limit:
        seconds: 10
        maxCount: 3
    # 文字自动转化为图片的长度，单位字符
    transToImageLength: 100

# 常规设置
setting:
    # 离线模式
    offline: false
