name: Bug 报告
description: 提交一个 bug
labels:
  - "bug"

body:
  - type: markdown
    attributes:
      value: |
        感谢你来到这里

        在反馈前, 请确认你已经做了下面这些事情且符合条件（如果有）
        - 搜索了已有的 [issues](https://github.com/AmiyaBot/Amiya-Bot/issues) 列表，其中没有相关的信息
        - 阅读了 [Amiya-Bot 的相关文档](https://github.com/mamoe/mirai/tree/dev/docs)

  - type: textarea
    id: issue-description
    attributes:
      label: 问题描述
      description: 在此详细描述你遇到的问题
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现
      description: 在这里简略说明如何让这个问题再次发生
      placeholder: |
        在这里简略说明如何让这个问题再次发生
        可使用 1.  2.  3.  的列表格式，或其他任意恰当的格式
        如果你不确定如何复现, 请尽量描述发生当时的情景
    validations:
      required: true

  - type: input
    id: version-amiya-bot
    attributes:
      label: Amiya-Bot 版本
      description: "填写你正在使用的版本号，如 `6.0.0-Beta3`"
      placeholder: 6.0.0-Beta3
    validations:
      required: true

  - type: textarea
    id: version-others
    attributes:
      label: 其他插件版本
      description: 如果你正在同时使用非官方的已在插件商店上架的插件, 请同样提供版本号
      placeholder: |
        example: `2.3.3`

  - type: textarea
    id: journal
    attributes:
      label: 日志
      description: |
        请提供全面的相关日志. 请不要截图.
        如果日志过大, 可以在 `补充信息` 上传文件.
      render: 'text'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 如有必要，你可以在下文继续添加其他信息

