blank_issues_enabled: false
contact_links:
  - name: 遇到非程序本身引发的问题？
    url: https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1W4sJux&appChannel=share&businessType=9&from=181074&biz=ka&shareSource=5
    about: 例如部署、配置遇到困难等，请选择此项
