operatorSetting:
    classes:
        CASTER: 术师
        MEDIC: 医疗
        PIONEER: 先锋
        SNIPER: 狙击
        SPECIAL: 特种
        SUPPORT: 辅助
        TANK: 重装
        WARRIOR: 近卫
    token_classes:
        TOKEN: 召唤物
        TRAP: 装置
    high_star:
        '5': 资深干员
        '6': 高级资深干员
    types:
        ALL: 不限部署位
        MELEE: 近战位
        RANGED: 远程位

materialSetting:
    rate:
        SOMETIMES: 罕见
        OFTEN: 小概率
        USUAL: 中概率
        ALMOST: 大概率
        ALWAYS: 固定
    made:
        WORKSHOP: [ '加工站', '合成' ]
        MANUFACTURE: [ '制造站', '生产' ]

jadeSetting:
    signIn: 200
    dailyTasks: 100
    weeklyTasks: 500
    weeklyBattle: 1800
