prefixName:
    - 阿米娅
    - 阿米兔
    - 兔兔
    - 兔子
    - 小兔子
    - Amiya
    - amiya

imageCreator:
    convertLength: 100
    fontFile: resource/style/AdobeHeitiStd-Regular.otf

speedSetting:
    maxsize: 3
    mintime: 10
