guess: '猜干员游戏'
checkEnemy: '敌人信息模块'
checkMaterial: '材料信息模块'
checkOperator: '干员信息模块'
gacha: '模拟抽卡'
intellectAlarm: '理智提醒'
jadeCalculator: '合成玉计算'
recruit: '公招'
textReplace: '词语替换'
user: '用户模块'
weibo: '微博模块'
covid: '新冠疫情查询'
wordle: '猜字谜游戏'
