remote:
    cos: https://cos.amiyabot.com
    wiki: https://static.prts.wiki
    gameData:
        version: https://gitee.com/vivien8261/Arknights-Bot-Resource/raw/main
        source: http://vivien8261.gitee.io/arknights-bot-resource
        files:
            - levels/enemydata/enemy_database.json
            - excel/enemy_handbook_table.json
            - excel/handbook_info_table.json
            - excel/battle_equip_table.json
            - excel/char_patch_table.json
            - excel/character_table.json
            - excel/uniequip_table.json
            - excel/charword_table.json
            - excel/building_data.json
            - excel/range_table.json
            - excel/gacha_table.json
            - excel/stage_table.json
            - excel/skill_table.json
            - excel/skin_table.json
            - excel/item_table.json

save:
    data: resource/data
    face: resource/images/face
    rank: resource/images/rank
    style: resource/style
    gacha: resource/images/gacha
    classify: resource/images/classify
    database: resource/database

files:
    face:
        - images/face/face1.png
        - images/face/face2.png
        - images/face/face3.png
        - images/face/face4.png
        - images/face/face5.png
        - images/face/face6.png
        - images/face/face7.png
        - images/face/face8.png
        - images/face/face9.png
        - images/face/face10.png
        - images/face/face11.png
        - images/face/face12.png
        - images/face/face13.png
        - images/face/face14.png
        - images/face/face15.png
        - images/face/face16.png

    rank:
        - images/rank/1.png
        - images/rank/2.png
        - images/rank/3.png
        - images/rank/4.png
        - images/rank/5.png
        - images/rank/6.png

    style:
        - font/AdobeHeitiStd-Regular.otf
        - font/rabbit.png
        - font/rabbit-white.png

    classify:
        - images/class/caster.png
        - images/class/medic.png
        - images/class/pioneer.png
        - images/class/sniper.png
        - images/class/special.png
        - images/class/support.png
        - images/class/tank.png
        - images/class/warrior.png

    gacha:
        - images/gacha/1.png
        - images/gacha/2.png
        - images/gacha/3.png
        - images/gacha/4.png
        - images/gacha/5.png
        - images/gacha/6.png
        - images/gacha/bg.png

    database: [ ]
