call:
    positive: [ '阿米娅','阿米兔','兔兔','兔子','小兔子','Amiya','amiya' ]
    inactive: [ '阿米驴', '阿驴', '小驴子', '驴子', '驴驴' ]

talk:
    positive:
        - '%s乖'
        - '%s真乖'
        - '%s真棒'
        - '%s萌'
        - '%s么么哒'
        - '爱%s'
        - '喜欢%s'
        - '我喜欢你'
        - '我爱你'
        - '亲'
        - '抱抱'
        - '抱一抱'
        - '抱一下'
        - '摸摸'
        - '摸头'
        - '摸摸头'
        - '太可爱了'
        - '真可爱'
        - '可爱'
        - '真漂亮'
        - '漂亮'
    inactive:
        - '不喜欢%s'
        - '讨厌%s'
        - '恨%s'
        - '透%s'
        - '日%s'
        - '爬'
        - '爪巴'
        - '滚'
        - '傻逼'
        - '煞笔'
        - '沙比'

stage:
    -   feeling: 4000
        text: 博士……我最近……是不是变得有点不像自己？那些偶然升起的无名怒火……是我的吗？就算这样，不，就算这样我也不会放弃。我会保护你的，博士，凭这把剑。
        voice: 阿米娅(近卫)_信赖提升后交谈3
    -   feeling: 3000
        text: 就算是现在，我也偶尔会想起米莎的眼神，想起霜星的怒吼，想起爱国者的嘶鸣……Ace、Scout以及许多干员为一个信念牺牲了自己。可大地上那么多的感染者，又是为了什么而死？
        voice: 阿米娅(近卫)_信赖提升后交谈2
    -   feeling: 2400
        text: 死亡应该铭刻在我们的记忆里，永不遗忘，无论这死亡是谁带来的，又是被带给了谁。我们的错误永远不会变成正确……那些疤痕应该要一直提醒我们，警告我们有多脆弱。
        voice: 阿米娅(近卫)_信赖提升后交谈1
    -   feeling: 2000
        text: 博士，我们的脚下，是一条漫长的道路……也许这是一次没有终点的旅行，但如果是和您一起，我觉得，非常幸福。
        voice: 阿米娅_信赖提升后交谈3
    -   feeling: 1000
        text: 嘿嘿，博士，悄悄告诉你一件事……我重新开始练小提琴了。是想在这次派对上给大家的惊喜，所以博士……要对大家保密哦
        voice: 阿米娅_信赖提升后交谈2
    -   feeling: 400
        text: 有时候，我会想起寒冷的家乡，那里就连空气中都弥漫着铜锈的味道。相比之下罗德岛是如此的温暖。所以，为了守护好这里，我必须更加努力才行。
        voice: 阿米娅_信赖提升后交谈1
    -   feeling: 0
        text: 博士，您工作辛苦了
        voice: 阿米娅_任命助理

touch:
    - 凯尔希医生教导过我，工作的时候一定要保持全神贯注……嗯，全神贯注。
    - 罗德岛全舰正处于通常航行状态。博士，整理下航程信息吧？
    - 作为罗德岛的领导者我还有很多不成熟的地方，希望您能更多地为我指明前进的方向。
    - 虽然这可能是我一厢情愿的想法，但我希望罗德岛能成为大家的第二个故乡……
    - 我们失去了很多才走到今天。有时候我会问自己，这一切真的值得么…？
    - 我是，Amiya，和姐姐一样的名字，所以，我也要和姐姐一样优秀。
    - 妈妈有时会和我提起姐姐，她总说姐姐去了很远的地方……可是，不在妈妈身边，姐姐会感到快乐吗？
    - 姐姐现在正在干什么呢……会不会有一天回来……
    - 姐姐以前似乎是人气很高的人呢，我也要继续努力，得到博士的认可。
    - 姐姐的日记里，记录着很多博士的信息。不知道博士们，还记不记得姐姐……
