name: Windows binary package

on:
    push:
        branches: [ V6-dev, V6-master ]
        paths: [ '.github/publish.txt' ]
    pull_request:
        branches: [ V6-dev, V6-master ]
        paths: [ '.github/publish.txt' ]

jobs:
    publish-package:
        runs-on: windows-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python 3.8.10 amd64
                uses: actions/setup-python@v4
                with:
                    python-version: 3.8.10
                    architecture: x64

            -   name: Get branch name
                id: branch-name
                uses: tj-actions/branch-names@v5.1

            -   name: Branch name
                run: |
                    echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m venv venv
                    venv\Scripts\python -m pip install --upgrade pip wheel setuptools
                    venv\Scripts\python -m pip install -r requirements.txt
                    venv\Scripts\python -m pip install cos-python-sdk-v5
                    venv\Scripts\python -m pip install pyinstaller

            -   name: Build and publish package
                env:
                    SECRETID: ${{ secrets.SECRETID }}
                    SECRETKEY: ${{ secrets.SECRETKEY }}
                run: |
                    venv\Scripts\Activate.ps1
                    venv\Scripts\python run_build.py --type package --branch ${{ steps.branch-name.outputs.current_branch }} --upload
