name: Publish packages

on:
    push:
        branches: [ V6-master ]
        paths: [ '.github/publish.txt' ]

    workflow_dispatch:

jobs:
    publish-windows-package:
        runs-on: windows-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Python 3.8.10 amd64
                uses: actions/setup-python@v4
                with:
                    python-version: 3.8.10
                    architecture: x64

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m venv venv
                    venv\Scripts\python -m pip install --upgrade pip wheel setuptools
                    venv\Scripts\python -m pip install -r requirements.txt
                    venv\Scripts\python -m pip install cos-python-sdk-v5
                    venv\Scripts\python -m pip install pyinstaller

            -   name: Build and publish package
                env:
                    SECRETID: ${{ secrets.SECRETID }}
                    SECRETKEY: ${{ secrets.SECRETKEY }}
                run: |
                    venv\Scripts\Activate.ps1
                    venv\Scripts\python run_build.py --type package --platform windows --upload

    publish-linux-package:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Python 3.8.10
                uses: actions/virtualenv@v2
                with:
                    python-version: 3.8
                id: virtualenv

            -   name: Activate Virtualenv
                run: source ${virtualenv}/bin/activate

            -   name: Install dependencies
                run: |
                    ${virtualenv}/bin/python -m pip install --upgrade pip wheel setuptools
                    ${virtualenv}/bin/python -m pip install -r requirements.txt
                    ${virtualenv}/bin/python -m pip install cos-python-sdk-v5
                    ${virtualenv}/bin/python -m pip install pyinstaller

            -   name: Build and publish package
                env:
                    SECRETID: ${{ secrets.SECRETID }}
                    SECRETKEY: ${{ secrets.SECRETKEY }}
                run: |
                    ${virtualenv}/bin/python run_build.py --type package --platform linux --upload
