name: Windows binary package

on:
    push:
        branches: [ V6-dev, V6-master ]
    pull_request:
        branches: [ V6-dev, V6-master ]

jobs:
    build-win-amd64:
        runs-on: windows-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python 3.8.10 amd64
                uses: actions/setup-python@v4
                with:
                    python-version: 3.8.10
                    architecture: x64

            -   name: Set vars
                id: vars
                run: |
                    echo ::set-output name=branch_name::${GITHUB_REF#refs/heads/}

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m venv venv
                    venv\Scripts\python -m pip install --upgrade pip wheel setuptools
                    venv\Scripts\python -m pip install -r requirements.txt
                    venv\Scripts\python -m pip install pyinstaller
                    venv\Scripts\python -m pip install cos-python-sdk-v5

            -   name: Publish package
                env:
                    SECRETID: ${{ secrets.SECRETID }}
                    SECRETKEY: ${{ secrets.SECRETKEY }}
                run: |
                    venv\Scripts\Activate.ps1
                    venv\Scripts\python build.py --branch ${{steps.vars.outputs.branch_name}}
