name: Windows binary package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3 amd64
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
        architecture: x64
        
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      shell: bash
      

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        venv\Scripts\python -m pip install --upgrade pip wheel setuptools
        venv\Scripts\python -m pip install -r requirements.txt
        venv\Scripts\python -m pip install pyinstaller
      shell: cmd
    - name: Make package
      shell: powershell
      run: |
        venv\Scripts\Activate.ps1  
        venv\Scripts\python build.py ${{steps.branch_name.outputs.SOURCE_TAG}}
    - name: release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{steps.branch_name.outputs.SOURCE_TAG}}
        prerelease: false
        title: ${{steps.branch_name.outputs.SOURCE_TAG}}
        files: |
          AmiyaBot-${{steps.branch_name.outputs.SOURCE_TAG}}.zip